org: hhassan
app: orbital-serverless
service: accounts-service

provider:
  name: aws
  runtime: nodejs20.x
  # region: us-east-1
  environment:
    MONGODB_URI: "mongodb+srv://root:orbital-password@orbital-test-0.5brqv.mongodb.net/?retryWrites=true&w=majority&appName=orbital-test-0"
    # MONGODB_URI: ${ssm:/accounts-service/MONGODB_URI}
    # EVENT_BUS_NAME: ${ssm:/my-service/EVENT_BUS_NAME~true}

functions:
  createAccount:
    handler: build/handlers/createAccount.handler
    events:
      - http:
          path: accounts
          method: post

  getAccount:
    handler: build/handlers/getAccount.handler
    events:
      - http:
          path: accounts/{accountId}
          method: get

  updateAccount:
    handler: build/handlers/updateAccount.handler
    events:
      - http:
          path: accounts/{accountId}
          method: put

  createTransaction:
    handler: build/handlers/createTransaction.handler
    events:
      - http:
          path: transactions
          method: post

  getTransactions:
    handler: build/handlers/getTransactions.handler
    events:
      - http:
          path: transactions/{accountId}
          method: get

package:
  exclude:
    - node_modules/**
    - src/tests/**
    - build/**

plugins:
  - serverless-offline
